name: MyNews
description: News App

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state managment
  scoped_model: ^1.0.1
  # newtork
  http: ^0.12.0+2
 
  # local storage
  shared_preferences: ^0.5.6+2
  sqflite: ^1.3.0
  path_provider: ^1.6.9
  # page transition animations
  page_transition: ^1.1.5
  # location
  geolocator: ^5.3.1
  # device
  url_launcher: ^5.4.2
  android_intent: ^0.3.7+2
  share: ^0.6.3+1
  flutter_email_sender: ^3.0.1
  fluttertoast: ^4.0.1
  # native plugins
  flutter_native_splash: ^0.1.9
  flutter_webview_plugin: ^0.3.11
  flutter_local_notifications: ^1.4.3
  # firebase 
  firebase_admob: ^0.9.3+2
  admob_flutter: ^0.3.4
  # helpers
  timeago: ^2.0.26
  device_preview: ^0.4.8
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter icons setup
flutter_icons:
  android: true 
  ios: true 
  image_path: "Assets/images/app-icon.png"

# flutter splash screen setup
flutter_native_splash:
  image: Assets/images/loading_screen_logo.png
  color: "#ffffff"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
 
  assets:
     - Assets/images/placeHolder.jpg
     - Assets/images/loading.jpg
     - Assets/images/app-icon.png
     - Assets/images/loading_screen_logo.png
     - Assets/images/splash-logo.png

  fonts:
      - family: Roboto
        fonts:
          - asset: Assets/Fonts/Roboto-Medium.ttf
            weight: 700

      
